tarting due to changes...
[nodemon] starting `node server.js`
C:\Users\rk170\Desktop\eduSaathi\backend\node_modules\@supabase\supabase-js\dist\index.cjs:146
        if (!trimmedUrl) throw new Error("supabaseUrl is required.");
                         ^

Error: supabaseUrl is required.
    at validateSupabaseUrl (C:\Users\rk170\Desktop\eduSaathi\backend\node_modules\@supabase\supabase-js\dist\index.cjs:146:25)
    at new SupabaseClient (C:\Users\rk170\Desktop\eduSaathi\backend\node_modules\@supabase\supabase-js\dist\index.cjs:362:19)
    at createClient (C:\Users\rk170\Desktop\eduSaathi\backend\node_modules\@supabase\supabase-js\dist\index.cjs:582:9)
    at Object.<anonymous> (C:\Users\rk170\Desktop\eduSaathi\backend\middleware\auth.js:7:18)
    at Module._compile (node:internal/modules/cjs/loader:1761:14)
    at Object..js (node:internal/modules/cjs/loader:1893:10)
    at Module.load (node:internal/modules/cjs/loader:1481:32)
    at Module._load (node:internal/modules/cjs/loader:1300:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)

Node.js v24.11.1
[nodemon] app crashed - waiting for file changes before starting...
